name: LeagueOfCrafters
authors: [AdamAguilera]
description: MOBA Plugin
version: 1.0
api-version: 1.17
main: leagueofcrafters.Main
commands:
  loc:
    description: This is som command
    usage: /loc <heroname>
